// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IdentityWebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ValueTupleStringString
    {
        /// <summary>
        /// Initializes a new instance of the ValueTupleStringString class.
        /// </summary>
        public ValueTupleStringString() { }

        /// <summary>
        /// Initializes a new instance of the ValueTupleStringString class.
        /// </summary>
        public ValueTupleStringString(string item1 = default(string), string item2 = default(string))
        {
            Item1 = item1;
            Item2 = item2;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Item1")]
        public string Item1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Item2")]
        public string Item2 { get; set; }

    }
}
