//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegacyWebApp.IdentityWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdentityWCF.IIdentityService")]
    public interface IIdentityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentityService/GetHeadersAndClaims", ReplyAction="http://tempuri.org/IIdentityService/GetHeadersAndClaimsResponse")]
        System.ValueTuple<System.ValueTuple<string, string>[], System.ValueTuple<string, string>[]> GetHeadersAndClaims();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentityService/GetHeadersAndClaims", ReplyAction="http://tempuri.org/IIdentityService/GetHeadersAndClaimsResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<System.ValueTuple<string, string>[], System.ValueTuple<string, string>[]>> GetHeadersAndClaimsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIdentityServiceChannel : LegacyWebApp.IdentityWCF.IIdentityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdentityServiceClient : System.ServiceModel.ClientBase<LegacyWebApp.IdentityWCF.IIdentityService>, LegacyWebApp.IdentityWCF.IIdentityService {
        
        public IdentityServiceClient() {
        }
        
        public IdentityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdentityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<System.ValueTuple<string, string>[], System.ValueTuple<string, string>[]> GetHeadersAndClaims() {
            return base.Channel.GetHeadersAndClaims();
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<System.ValueTuple<string, string>[], System.ValueTuple<string, string>[]>> GetHeadersAndClaimsAsync() {
            return base.Channel.GetHeadersAndClaimsAsync();
        }
    }
}
